"""add error message to documents

Revision ID: 84fbd72ab35e
Revises: f6e19b06896d
Create Date: 2026-08-09 14:10:58.334946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84fbd72ab35e'
down_revision: Union[str, Sequence[str], None] = 'f6e19b06896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.alter_column('documents', 'document_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'document_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###
